# Generated by Django 5.2.7 on 2025-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
