# Generated by Django 5.2.7 on 2025-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permite_reabrir_citas',
            field=models.BooleanField(default=True, help_text='Si está activo, una cita cancelada vuelve a quedar disponible.'),
        ),
    ]
